import pandas as pd


class DataStruct:
    def __init__(self) -> None:
        self.joint_ang_template = {
            "markers": {
                "hip_flex": pd.DataFrame(),
                "hip_ad_ab": pd.DataFrame(),
                "hip_rot": pd.DataFrame(),
                "knee_flex": pd.DataFrame(),
                "ank_flex": pd.DataFrame(),
                "ank_ev_inv": pd.DataFrame(),
                "lumbar_extension": pd.DataFrame(),
                "lumbar_bending": pd.DataFrame(),
                "lumbar_rotation": pd.DataFrame(),
            },
            "markerless": {
                "hip_flex": pd.DataFrame(),
                "hip_ad_ab": pd.DataFrame(),
                "hip_rot": pd.DataFrame(),
                "knee_flex": pd.DataFrame(),
                "ank_flex": pd.DataFrame(),
                "ank_ev_inv": pd.DataFrame(),
                "lumbar_extension": pd.DataFrame(),
                "lumbar_bending": pd.DataFrame(),
                "lumbar_rotation": pd.DataFrame(),
            },
        }

        self.segment_ang_template = {
            "markers": {
                "torso_x": pd.DataFrame(),
                "torso_y": pd.DataFrame(),
                "torso_z": pd.DataFrame(),
                "pelvis_x": pd.DataFrame(),
                "pelvis_y": pd.DataFrame(),
                "pelvis_z": pd.DataFrame(),
                "femur_x": pd.DataFrame(),
                "femur_y": pd.DataFrame(),
                "femur_z": pd.DataFrame(),
                "tibia_x": pd.DataFrame(),
                "tibia_y": pd.DataFrame(),
                "tibia_z": pd.DataFrame(),
                "calcn_x": pd.DataFrame(),
                "calcn_y": pd.DataFrame(),
                "calcn_z": pd.DataFrame(),
                "humerus_x": pd.DataFrame(),
                "humerus_y": pd.DataFrame(),
                "humerus_z": pd.DataFrame(),
                "ulna_x": pd.DataFrame(),
                "ulna_y": pd.DataFrame(),
                "ulna_z": pd.DataFrame(),
            },
            "markerless": {
                "torso_x": pd.DataFrame(),
                "torso_y": pd.DataFrame(),
                "torso_z": pd.DataFrame(),
                "pelvis_x": pd.DataFrame(),
                "pelvis_y": pd.DataFrame(),
                "pelvis_z": pd.DataFrame(),
                "femur_x": pd.DataFrame(),
                "femur_y": pd.DataFrame(),
                "femur_z": pd.DataFrame(),
                "tibia_x": pd.DataFrame(),
                "tibia_y": pd.DataFrame(),
                "tibia_z": pd.DataFrame(),
                "calcn_x": pd.DataFrame(),
                "calcn_y": pd.DataFrame(),
                "calcn_z": pd.DataFrame(),
                "humerus_x": pd.DataFrame(),
                "humerus_y": pd.DataFrame(),
                "humerus_z": pd.DataFrame(),
                "ulna_x": pd.DataFrame(),
                "ulna_y": pd.DataFrame(),
                "ulna_z": pd.DataFrame(),
            },
        }

        self.joint_centre_template = {
            "markers": {
                "sho_x": pd.DataFrame(),
                "sho_y": pd.DataFrame(),
                "sho_z": pd.DataFrame(),
                "hip_x": pd.DataFrame(),
                "hip_y": pd.DataFrame(),
                "hip_z": pd.DataFrame(),
                "knee_x": pd.DataFrame(),
                "knee_y": pd.DataFrame(),
                "knee_z": pd.DataFrame(),
                "ank_x": pd.DataFrame(),
                "ank_y": pd.DataFrame(),
                "ank_z": pd.DataFrame(),
            },
            "markerless": {
                "sho_x": pd.DataFrame(),
                "sho_y": pd.DataFrame(),
                "sho_z": pd.DataFrame(),
                "hip_x": pd.DataFrame(),
                "hip_y": pd.DataFrame(),
                "hip_z": pd.DataFrame(),
                "knee_x": pd.DataFrame(),
                "knee_y": pd.DataFrame(),
                "knee_z": pd.DataFrame(),
                "ank_x": pd.DataFrame(),
                "ank_y": pd.DataFrame(),
                "ank_z": pd.DataFrame(),
            },
        }
